sudo: required
services:
    - docker

before_install:
    - docker build -t docker-react-image -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react-image npm run test  -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-test"
    env: "DockerTest-env"
    bucket_name: "elasticbeanstalk-us-east-2-888346999907"
    bucket_path: "docker-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
